name: Run server unit tests

on:
  push:
    branches: ["main"]
    paths: ["server/**"]
  pull_request:
    branches: ["main"]
    paths: ["server/**"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"

      - name: Run tests and generate coverage report
        working-directory: server
        run: go test -v ./...
